#!/bin/bash
REPO="https://h00.ha-vps.store/"
wget -q -O /etc/systemd/system/limitvmess.service "${REPO}xray/limit/1" && chmod +x limitvmess.service >/dev/null 2>&1
wget -q -O /etc/systemd/system/limitvless.service "${REPO}xray/limit/2" && chmod +x limitvless.service >/dev/null 2>&1
wget -q -O /etc/systemd/system/limittrojan.service "${REPO}xray/limit/3" && chmod +x limittrojan.service >/dev/null 2>&1
wget -q -O /etc/systemd/system/limitshadowsocks.service "${REPO}xray/limit/4" && chmod +x limitshadowsocks.service >/dev/null 2>&1
wget -q -O /etc/xray/limit.vmess "${REPO}xray/limit/vmess" >/dev/null 2>&1
wget -q -O /etc/xray/limit.vless "${REPO}xray/limit/vless" >/dev/null 2>&1
wget -q -O /etc/xray/limit.trojan "${REPO}xray/limit/trojan" >/dev/null 2>&1
wget -q -O /etc/xray/limit.shadowsocks "${REPO}xray/limit/shadowsocks" >/dev/null 2>&1
chmod +x /etc/xray/limit.vmess
chmod +x /etc/xray/limit.vless
chmod +x /etc/xray/limit.trojan
chmod +x /etc/xray/limit.shadowsocks
systemctl daemon-reload
systemctl enable limitvmess
systemctl enable limitvless
systemctl enable limittrojan
systemctl enable limitshadowsocks
systemctl start limitvmess
systemctl start limitvless
systemctl start limittrojan
systemctl start limitshadowsocks
systemctl restart limitvmess
systemctl restart limitvless
systemctl restart limittrojan
systemctl restart limitshadowsocks
systemctl restart ssh
systemctl restart sshd
